In [3]:
import pandas as pd
from collections import Counter

In [4]:
df = pd.read_csv("../../../data/celeba/original_merged.csv")

# Preparing the dataset for Train/val/test

In [6]:
# sample 80% of the data for train and 20% for test
train = df.sample(frac=0.8, random_state=42)
test = df.drop(train.index)
train.to_csv("../../../data/celeba/train_with_validation.csv", index=False)
test.to_csv("../../../data/celeba/test.csv", index=False)

# sample 20% of the training data for validation
train = pd.read_csv("../../../data/celeba/train_with_validation.csv")
val = train.sample(frac=0.2, random_state=42)
train = train.drop(val.index)
train.to_csv("../../../data/celeba/train.csv", index=False)
val.to_csv("../../../data/celeba/validation.csv", index=False)

# Hair

In [46]:
len(df)

202599

In [47]:
Counter(df["Smiling"])

Counter({1: 97669, -1: 104930})

In [48]:
# show all the columns without truncation
pd.set_option("display.max_columns", None)

In [49]:
df.head()

,image_id,5_o_Clock_Shadow,Arched_Eyebrows,Attractive,Bags_Under_Eyes,Bald,Bangs,Big_Lips,Big_Nose,Black_Hair,Blond_Hair,Blurry,Brown_Hair,Bushy_Eyebrows,Chubby,Double_Chin,Eyeglasses,Goatee,Gray_Hair,Heavy_Makeup,High_Cheekbones,Male,Mouth_Slightly_Open,Mustache,Narrow_Eyes,No_Beard,Oval_Face,Pale_Skin,Pointy_Nose,Receding_Hairline,Rosy_Cheeks,Sideburns,Smiling,Straight_Hair,Wavy_Hair,Wearing_Earrings,Wearing_Hat,Wearing_Lipstick,Wearing_Necklace,Wearing_Necktie,Young,split,Target
0,000001.jpg,-1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,1,-1,1,-1,-1,1,-1,-1,1,-1,-1,-1,1,1,-1,1,-1,1,-1,-1,1,0.137514,1
1,000002.jpg,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,1,-1,1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,1,-0.432273,1
2,000003.jpg,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,1,1,-1,-1,1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,1,1.841473,0
3,000004.jpg,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,1,-1,-1,-1,-1,1,-1,1,-1,1,1,-1,1,-0.080797,1
4,000005.jpg,-1,1,1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,1,1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,1,1.045482,1

In [50]:
df.columns

Index(['image_id', '5_o_Clock_Shadow', 'Arched_Eyebrows', 'Attractive',
       'Bags_Under_Eyes', 'Bald', 'Bangs', 'Big_Lips', 'Big_Nose',
       'Black_Hair', 'Blond_Hair', 'Blurry', 'Brown_Hair', 'Bushy_Eyebrows',
       'Chubby', 'Double_Chin', 'Eyeglasses', 'Goatee', 'Gray_Hair',
       'Heavy_Makeup', 'High_Cheekbones', 'Male', 'Mouth_Slightly_Open',
       'Mustache', 'Narrow_Eyes', 'No_Beard', 'Oval_Face', 'Pale_Skin',
       'Pointy_Nose', 'Receding_Hairline', 'Rosy_Cheeks', 'Sideburns',
       'Smiling', 'Straight_Hair', 'Wavy_Hair', 'Wearing_Earrings',
       'Wearing_Hat', 'Wearing_Lipstick', 'Wearing_Necklace',
       'Wearing_Necktie', 'Young', 'split', 'Target'],
      dtype='object')

In [51]:
# for each column show the number of unique values
df.nunique()

image_id               202599
5_o_Clock_Shadow            2
Arched_Eyebrows             2
Attractive                  2
Bags_Under_Eyes             2
Bald                        2
Bangs                       2
Big_Lips                    2
Big_Nose                    2
Black_Hair                  2
Blond_Hair                  2
Blurry                      2
Brown_Hair                  2
Bushy_Eyebrows              2
Chubby                      2
Double_Chin                 2
Eyeglasses                  2
Goatee                      2
Gray_Hair                   2
Heavy_Makeup                2
High_Cheekbones             2
Male                        2
Mouth_Slightly_Open         2
Mustache                    2
Narrow_Eyes                 2
No_Beard                    2
Oval_Face                   2
Pale_Skin                   2
Pointy_Nose                 2
Receding_Hairline           2
Rosy_Cheeks                 2
Sideburns                   2
Smiling                     2
Straight_Hair               2
Wavy_Hair                   2
Wearing_Earrings            2
Wearing_Hat                 2
Wearing_Lipstick            2
Wearing_Necklace            2
Wearing_Necktie             2
Young                       2
split                  202599
Target                     10
dtype: int64

# Hair Color

In [52]:
black_Hair = df["Black_Hair"]
blond_Hair = df["Blond_Hair"]
brown_Hair = df["Brown_Hair"]
gray_Hair = df["Gray_Hair"]
bald = df["Bald"]

In [53]:
black_Hair = [0 if i == 1 else -1 for i in black_Hair]
blond_Hair = [1 if i == 1 else -1 for i in blond_Hair]
brown_Hair = [2 if i == 1 else -1 for i in brown_Hair]
gray_Hair = [3 if i == 1 else -1 for i in gray_Hair]
bald = [4 if i == 1 else -1 for i in bald]

In [54]:
hair_color = [-2] * len(black_Hair)
multiple_colors = 0
for index, _ in enumerate(hair_color):
    num_colors = 0
    color = -2
    if black_Hair[index] != -1:
        color = black_Hair[index]
        num_colors += 1

    if blond_Hair[index] != -1:
        color = blond_Hair[index]
        num_colors += 1

    if brown_Hair[index] != -1:
        color = brown_Hair[index]
        num_colors += 1

    if gray_Hair[index] != -1:
        color = gray_Hair[index]
        num_colors += 1

    if bald[index] != -1:
        color = bald[index]
        num_colors += 1

    if num_colors > 1:
        color = -2
    hair_color[index] = color

    multiple_colors += 1 if num_colors > 1 else 0

print(f"There are {multiple_colors} people with multiple hair colors")
no_colors = Counter(hair_color)[-2]
print(f"There are {no_colors} people with no hair color")

counter_colors = Counter(hair_color)
print(f"People with black hair: {counter_colors[0]}")
print(f"People with blond hair: {counter_colors[1]}")
print(f"People with brown hair: {counter_colors[2]}")
print(f"People with gray hair: {counter_colors[3]}")
print(f"People BALD: {counter_colors[4]}")

print(
    f"Total people with hair color: {len(hair_color) - no_colors} - People with only a single hair color: {len(hair_color) - no_colors - multiple_colors} - Total Dataset size: {len(hair_color)}"
)

There are 4088 people with multiple hair colors
There are 77707 people with no hair color
People with black hair: 47264
People with blond hair: 28251
People with brown hair: 39165
People with gray hair: 6828
People BALD: 3384
Total people with hair color: 124892 - People with only a single hair color: 120804 - Total Dataset size: 202599

In [55]:
Counter(hair_color)

Counter({2: 39165, -2: 77707, 0: 47264, 1: 28251, 3: 6828, 4: 3384})

In [56]:
df["Hair_Color"] = hair_color
df = df[df["Hair_Color"] != -2]

In [57]:
df.head()

,image_id,5_o_Clock_Shadow,Arched_Eyebrows,Attractive,Bags_Under_Eyes,Bald,Bangs,Big_Lips,Big_Nose,Black_Hair,Blond_Hair,Blurry,Brown_Hair,Bushy_Eyebrows,Chubby,Double_Chin,Eyeglasses,Goatee,Gray_Hair,Heavy_Makeup,High_Cheekbones,Male,Mouth_Slightly_Open,Mustache,Narrow_Eyes,No_Beard,Oval_Face,Pale_Skin,Pointy_Nose,Receding_Hairline,Rosy_Cheeks,Sideburns,Smiling,Straight_Hair,Wavy_Hair,Wearing_Earrings,Wearing_Hat,Wearing_Lipstick,Wearing_Necklace,Wearing_Necktie,Young,split,Target,Hair_Color
0,000001.jpg,-1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,1,-1,1,-1,-1,1,-1,-1,1,-1,-1,-1,1,1,-1,1,-1,1,-1,-1,1,0.137514,1,2
1,000002.jpg,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,1,-1,1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,1,-0.432273,1,2
5,000006.jpg,-1,1,1,-1,-1,-1,1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,-1,-1,1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,1,1,-1,1,-1,-1,1,0.262486,1,2
6,000007.jpg,1,-1,1,1,-1,-1,1,1,1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,1,-1,-1,-1,-1,1,-1,-1,-1,-1,-1,-1,1,-0.176136,0,0
7,000008.jpg,1,1,-1,1,-1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-1,-1,-1,1,-1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,-0.094506,0,0

In [58]:
df.shape

(124892, 44)

In [59]:
df["Hair_Color"].value_counts()

0    47264
2    39165
1    28251
3     6828
4     3384
Name: Hair_Color, dtype: int64

# Hair Color, Target: Attractive

In [60]:
for i in range(5):
    print(
        f"Hair Color {i}, Attractive=1",
        df[(df["Hair_Color"] == i) & (df["Attractive"] == 1)].shape[0],
    )
    print(
        f"Hair Color {i}, Attractive=0",
        df[(df["Hair_Color"] == i) & (df["Attractive"] == -1)].shape[0],
    )

Hair Color 0, Attractive=1 24239
Hair Color 0, Attractive=0 23025
Hair Color 1, Attractive=1 19991
Hair Color 1, Attractive=0 8260
Hair Color 2, Attractive=1 25072
Hair Color 2, Attractive=0 14093
Hair Color 3, Attractive=1 174
Hair Color 3, Attractive=0 6654
Hair Color 4, Attractive=1 136
Hair Color 4, Attractive=0 3248

In [61]:
df.shape

(124892, 44)

In [62]:
df.to_csv("../../../data/celeba_hair/attractive.csv")

# Blonde vs Not Blonde

In [227]:
blonde = [1 if item == 2 else 0 for item in df["Hair_Color"]]
df["Hair_Color"] = blonde

In [228]:
df["Hair_Color"].value_counts()

0    73661
1    35275
Name: Hair_Color, dtype: int64

In [229]:
gender = [1 if item == 1 else 0 for item in df["Male"]]
df["Gender"] = gender

In [230]:
df["Gender"].value_counts()

0    77459
1    31477
Name: Gender, dtype: int64

In [231]:
df[(df["Hair_Color"] == 1) & (df["Gender"] == 0)].shape[0]

27072

In [232]:
df[(df["Hair_Color"] == 1) & (df["Gender"] == 1)].shape[0]

8203

In [233]:
df[(df["Hair_Color"] == 0) & (df["Gender"] == 0)].shape[0]

50387

In [234]:
df[(df["Hair_Color"] == 0) & (df["Gender"] == 1)].shape[0]

23274

In [235]:
df.to_csv("../../../data/celeba_hair/blonde_hair.csv")

In [236]:
df.shape

(108936, 45)

In [ ]:
# color_gender = [
#     (color, gender) for color, gender in zip(list(df["Hair_Color"]), list(df["Gender"]))
# ]


# print(Counter(color_gender))
# list(Counter(color_gender).keys())

# combinations = list(Counter(color_gender).keys())
# values = [0,1,2,3,4,5,6,7]
# sens_attribute = []

# for key in color_gender:
#     index = combinations.index(key)
#     sens_attribute.append(values[index])

In [ ]:
# df["Gender"] = sens_attribute

In [ ]:
df["Hair_Color"].value_counts()

In [ ]:
df["Smiling"].value_counts()

In [ ]:
df["Gender"].value_counts()

In [ ]:
df.to_csv("../../../data/celeba_hair/hair_color_smiling.csv")

In [ ]:
df.shape

In [ ]:
df["Hair_Color"].value_counts()

In [ ]:
color_names = []
for item in list(df["Hair_Color"]):
    if item == 0:
        color_names.append("Black")
    elif item == 1:
        color_names.append("Blonde")
    elif item == 2:
        color_names.append("Brown")
    elif item == 3:
        color_names.append("Gray")

In [ ]:
df.head()

In [ ]:
gender = ["Male" if item == 1 else "Female" for item in df["Male"]]

In [ ]:
color_gender = [(color, gender) for color, gender in zip(color_names, gender)]
Counter(color_gender)

In [ ]:
Counter(list(df["Hair_Color"]))

In [ ]:
hair_color = list(df["Hair_Color"])
hair_color = [1 if item == 1 else 0 for item in hair_color]
df["Hair_Color"] = hair_color

In [ ]:
Counter(hair_color)

In [ ]:
color_gender = [(color, gender) for color, gender in zip(list(df["Hair_Color"]), list(df["Gender"]))]
Counter(color_gender)

In [ ]:
color_gender = [(color, gender) for color, gender in zip(list(df["Hair_Color"]), list(df["Gender"]))]
Counter(color_gender)
for key, value in Counter(color_gender).items():
    print("color: ", key[0], " gender: ", key[1], " count: ", value)

print("Gender == 0 ", Counter(color_gender)[(0, 0)] + Counter(color_gender)[(1, 0)])
print("Gender == 1 ", Counter(color_gender)[(0, 1)] + Counter(color_gender)[(1, 1)])

print("Color == 0 ", Counter(color_gender)[(0, 0)] + Counter(color_gender)[(0, 0)])
print("Color == 1 ", Counter(color_gender)[(1, 1)] + Counter(color_gender)[(1, 0)])

In [ ]:
df.shape

In [ ]:
# df.to_csv("../dataset/celeba/celeba_hair_merged.csv", index=False)

# # # split in train and test
# # train = df.sample(frac=0.8, random_state=200)
# # test = df.drop(train.index)
# # validation = train.sample(frac=0.2, random_state=200)
# # train_validation = train.drop(validation.index)

# # train.to_csv("../dataset/celeba/train_hair.csv", index=False)
# # validation.to_csv("../dataset/celeba/validation_hair.csv", index=False)
# # test.to_csv("../dataset/celeba/test_hair.csv", index=False)
# # train_validation.to_csv("../dataset/celeba/train_with_validation_hair.csv", index=False)

In [ ]:
# # check
# ddf = pd.read_csv("../dataset/celeba/celeba_hair_merged.csv")
# print(Counter(list(ddf["Gender"])))
# print(Counter(list(ddf["Hair_Color"])))

In [ ]:
df.shape

In [ ]:
df["Smiling"].value_counts()

In [ ]:
gender_attractive_haircolor = [
    (gender, attractive, hair_color)
    for gender, attractive, hair_color in zip(list(df["Gender"]), list(df["Attractive"]), list(df["Hair_Color"]))
]
print(Counter(gender_attractive_haircolor))
list(Counter(gender_attractive_haircolor).keys())

combinations = list(Counter(gender_attractive_haircolor).keys())
values = [0, 1, 2, 3, 4, 5, 6, 7]
sens_attribute = []

for key in gender_attractive_haircolor:
    index = combinations.index(key)
    sens_attribute.append(values[index])

In [ ]:
df["Gender"] = sens_attribute

In [ ]:
df["Gender"].value_counts()

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
df.to_csv("../../../data/celeba_hair/smiling_8_sens.csv")

In [ ]:
import copy

celeba_hair_original = copy.copy(df)

In [ ]:
df = df.drop(df[df["Hair_Color"] == 0].sample(frac=0.3).index)
df.shape

In [ ]:
df["Hair_Color"].value_counts()

In [ ]:
color_gender = [(color, gender) for color, gender in zip(list(df["Hair_Color"]), list(df["Gender"]))]
Counter(color_gender)
for key, value in Counter(color_gender).items():
    print("color: ", key[0], " gender: ", key[1], " count: ", value)

print("Gender == 0 ", Counter(color_gender)[(0, 0)] + Counter(color_gender)[(1, 0)])
print("Gender == 1 ", Counter(color_gender)[(0, 1)] + Counter(color_gender)[(1, 1)])

print("Color == 0 ", Counter(color_gender)[(0, 0)] + Counter(color_gender)[(0, 0)])
print("Color == 1 ", Counter(color_gender)[(1, 1)] + Counter(color_gender)[(1, 0)])

In [ ]:
gender_attractive_smiling = [
    (gender, attractive, smiling)
    for gender, attractive, smiling in zip(list(df["Gender"]), list(df["Attractive"]), list(df["Smiling"]))
]

In [ ]:
list(Counter(gender_attractive_smiling).keys())

In [ ]:
combinations = list(Counter(gender_attractive_smiling).keys())
values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
sens_attribute = []

for key in gender_attractive_smiling:
    index = combinations.index(key)
    sens_attribute.append(values[index])

In [ ]:
df["Gender"] = sens_attribute

In [ ]:
df["Gender"].value_counts()

In [ ]:
df["Hair_Color"].value_counts()

In [ ]:
df.head()

In [ ]:
df.to_csv("../../../data/celeba_hair/celeba_hair_9_attributes.csv", index=False)

In [ ]:
# df.to_csv("../../../data/celeba_hair/celeba_hair_reduced.csv", index=False)
# df = pd.read_csv("../../../data/celeba_hair/celeba_hair_reduced.csv")
# df.shape

In [ ]:
# class_0_samples = df[df["Hair_Color"] == 0].sample(n=28252, random_state=42)
# class_1_samples = df[df["Hair_Color"] == 1]

# balanced_df = pd.concat([class_0_samples, class_1_samples])
# balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [ ]:
# balanced_df.head()

In [ ]:
# balanced_df.shape

In [ ]:
# color_gender = [
#     (color, gender)
#     for color, gender in zip(
#         list(balanced_df["Hair_Color"]), list(balanced_df["Gender"])
#     )
# ]
# Counter(color_gender)

In [ ]:
# balanced_df.shape

# Multi - Balanced

In [ ]:
balanced_df.shape

In [ ]:
sens_attr = []
for smiling, gender in zip(list(balanced_df["Smiling"]), list(balanced_df["Gender"])):
    if smiling == 1 and gender == 1:
        sens_attr.append(0)
    elif smiling == -1 and gender == 1:
        sens_attr.append(1)
    elif smiling == 1 and gender == 0:
        sens_attr.append(2)
    else:
        sens_attr.append(3)

balanced_df["Sensitive_Attribute"] = sens_attr
print(Counter(sens_attr))

In [ ]:
# smiling_gender = []
# for smiling, gender, color in zip(
#     list(celeba_hair_original["Smiling"]),
#     list(celeba_hair_original["Gender"]),
#     list(celeba_hair_original["Hair_Color"]),
# ):
#     smiling_gender.append((smiling, gender, color))
# print(Counter(smiling_gender))

In [ ]:
# smiling_gender = []
# for sensitive_attribute, color in zip(
#     list(celeba_hair_original["Sensitive_Attribute"]), list(celeba_hair_original["Hair_Color"])
# ):
#     smiling_gender.append((sensitive_attribute, color))
# print(Counter(smiling_gender))

In [ ]:
# for key, value in Counter(color_gender).items():
#     print("color: ", key[0], " gender: ", key[1], " count: ", value)

# print("Gender == 0 ", Counter(color_gender)[(0, 0)] + Counter(color_gender)[(1, 0)])
# print("Gender == 1 ", Counter(color_gender)[(0, 1)] + Counter(color_gender)[(1, 1)])

# print("Color == 0 ", Counter(color_gender)[(0, 0)] + Counter(color_gender)[(0, 0)])
# print("Color == 1 ", Counter(color_gender)[(1, 1)] + Counter(color_gender)[(1, 0)])

In [ ]:
balanced_df["Gender"] = sens_attr

In [ ]:
Counter(balanced_df["Gender"])

In [ ]:
df = balanced_df.drop(
    balanced_df[(balanced_df["Gender"] == 0) & (balanced_df["Hair_Color"] == 0)].sample(frac=0.9).index
)

Counter(list(df["Gender"]))

In [ ]:
df.to_csv("../../../data/celeba_hair/celeba_hair_balanced_multiple_more_data.csv", index=False)
df = pd.read_csv("../../../data/celeba_hair/celeba_hair_balanced_multiple_more_data.csv")

Counter(list(df["Gender"]))

In [ ]:
Counter(list(df[df["Gender"] == 0]["Hair_Color"]))

In [ ]:
Counter(list(df["Hair_Color"]))

In [ ]:
df.shape

In [ ]:
# balanced_df.to_csv("../../../data/celeba_hair/celeba_hair_multiple.csv", index=False)

# Multi sensitive attribute

In [ ]:
celeba_hair_original.shape

In [ ]:
sens_attr = []
for smiling, gender in zip(list(celeba_hair_original["Smiling"]), list(celeba_hair_original["Gender"])):
    if smiling == 1 and gender == 1:
        sens_attr.append(0)
    elif smiling == -1 and gender == 1:
        sens_attr.append(1)
    elif smiling == 1 and gender == 0:
        sens_attr.append(2)
    else:
        sens_attr.append(3)

celeba_hair_original["Sensitive_Attribute"] = sens_attr
print(Counter(sens_attr))

In [ ]:
# smiling_gender = []
# for smiling, gender, color in zip(
#     list(celeba_hair_original["Smiling"]),
#     list(celeba_hair_original["Gender"]),
#     list(celeba_hair_original["Hair_Color"]),
# ):
#     smiling_gender.append((smiling, gender, color))
# print(Counter(smiling_gender))

In [ ]:
# smiling_gender = []
# for sensitive_attribute, color in zip(
#     list(celeba_hair_original["Sensitive_Attribute"]), list(celeba_hair_original["Hair_Color"])
# ):
#     smiling_gender.append((sensitive_attribute, color))
# print(Counter(smiling_gender))

In [ ]:
# for key, value in Counter(color_gender).items():
#     print("color: ", key[0], " gender: ", key[1], " count: ", value)

# print("Gender == 0 ", Counter(color_gender)[(0, 0)] + Counter(color_gender)[(1, 0)])
# print("Gender == 1 ", Counter(color_gender)[(0, 1)] + Counter(color_gender)[(1, 1)])

# print("Color == 0 ", Counter(color_gender)[(0, 0)] + Counter(color_gender)[(0, 0)])
# print("Color == 1 ", Counter(color_gender)[(1, 1)] + Counter(color_gender)[(1, 0)])

In [ ]:
celeba_hair_original["Gender"] = sens_attr

In [ ]:
Counter(celeba_hair_original["Gender"])

In [ ]:
df = celeba_hair_original.drop(
    celeba_hair_original[(celeba_hair_original["Gender"] == 0) & (celeba_hair_original["Hair_Color"] == 0)]
    .sample(frac=0.9)
    .index
)

Counter(list(df["Gender"]))

In [ ]:
df.to_csv("../../../data/celeba_hair/celeba_hair_multiple_more_data.csv", index=False)
df = pd.read_csv("../../../data/celeba_hair/celeba_hair_multiple_more_data.csv")

Counter(list(df["Gender"]))

In [ ]:
Counter(list(df[df["Gender"] == 0]["Hair_Color"]))

In [ ]:
Counter(list(df["Hair_Color"]))

In [ ]:
df.shape

In [ ]:
# balanced_df.to_csv("../../../data/celeba_hair/celeba_hair_multiple.csv", index=False)

In [ ]:
balanced_df.shape

# celeba_hair_balanced_multiple_more_data

In [ ]:
df = pd.read_csv("../../../data/celeba_hair/celeba_hair_balanced_multiple_more_data.csv")

In [ ]:
df.shape

In [ ]:
from collections import Counter

Counter(list(df["Gender"]))

In [ ]:
Counter(list(df["Hair_Color"]))